force-app/main/default/objects/Contact/fields/Emergency_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Name__c</fullName>
    <label>Emergency Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Emergency_Contact_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Relationship__c</fullName>
    <label>Emergency Contact Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Room must be a cubicle or personal office.</errorMessage>
        <filterItems>
            <field>Room__c.Room_Type__c</field>
            <operation>equals</operation>
            <value>Cubicle, Personal Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Occupants</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Facility ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/Facility_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Name__c</fullName>
    <label>Facility Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Facility__c/fields/Facility_Status__c.field-meta.xml
<CustomField>
    <fullName>Facility_Status__c</fullName>
    <label>Facility Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Facility__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <label>Room Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closet</fullName>
            </value>
            <value>
                <fullName>Communal Space</fullName>
            </value>
            <value>
                <fullName>Conference Room</fullName>
            </value>
            <value>
                <fullName>Cubicle</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Lavatory</fullName>
            </value>
            <value>
                <fullName>Personal Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Needs Cleaning</fullName>
            </value>
            <value>
                <fullName>Cleaning in Process</fullName>
            </value>
            <value>
                <fullName>Clean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room__c/recordTypes/Room.recordType-meta.xml
<RecordType>
    <fullName>Room</fullName>
    <active>true</active>
    <label>Room</label>
</RecordType>

force-app/main/default/objects/User/fields/Contact_Record__c.field-meta.xml
<CustomField>
    <fullName>Contact_Record__c</fullName>
    <label>Contact Record</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Confirmation__c/Visit_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Visit Confirmation</label>
    <nameField>
        <displayFormat>VID-{0000}</displayFormat>
        <label>Visit Confirmation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Confirmations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Confirmation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visit Confirmations</relationshipLabel>
    <relationshipName>Visit_Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Confirmation__c/fields/Event_Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_DateTime__c</fullName>
    <label>Event Start DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit_Confirmation__c/fields/Event_Subject__c.field-meta.xml
<CustomField>
    <fullName>Event_Subject__c</fullName>
    <label>Event Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Confirmation__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Visit Confirmations</relationshipLabel>
    <relationshipName>Visit_Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Confirmation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Visit Confirmations</relationshipLabel>
    <relationshipName>Visit_Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VisitConfirmationApexTests.cls
@isTest 
public with sharing class VisitConfirmationApexTests {

    @isTest static void CreateIndividualVisitConfirmationTests() {

        Account newAccount = new Account();
        newAccount.Name='Test Account' ;
        insert newAccount;

        Contact newContact = new Contact();
        newContact.FirstName='Test' ;
        newContact.LastName='Test' ;
        newContact.Account = newAccount;
        newContact.Emergency_Contact_Relationship__c = 'Spouse';
        newContact.Emergency_Contact_Name__c = 'Test';
        insert newContact;

        User thisUser = [SELECT Id, Contact_Record__c FROM User WHERE Id = :UserInfo.getUserId()];
        thisUser.Contact_Record__c = newContact.Id;
        update thisUser;


        Facility__c newFacility = new Facility__c();
        newFacility.Name = 'RES';
        newFacility.Facility_Name__c = 'Reston Office';
        newFacility.City__c = 'San Francisco';
        newFacility.Country__c = 'USA';
        newFacility.County__c = 'Fairfax County, VA';
        newFacility.State_Province__c = 'CA';
        newFacility.Street__c = '11720 Plaza America Dr.';
        newFacility.Zip_Postal_Code__c = '20190';
        newFacility.Facility_Status__c = 'Open';
        insert newFacility;

        Room__c newRoom = new Room__c();
        newRoom.Name = 'RES-8-001';
        newRoom.Room_Type__c = 'Conference Room';
        newRoom.Status__c = 'Clean';
        newRoom.Facility__c = newFacility.Id;
        insert newRoom;        

        Visit_Confirmation__c newVisitConfirmation = new Visit_Confirmation__c();
        newVisitConfirmation.OwnerId = UserInfo.getUserId();
        newVisitConfirmation.Event_Start_DateTime__c =  DateTime.now();
        newVisitConfirmation.Event_Subject__c = 'GDIT Discussion';
        newVisitConfirmation.Contact__c = newContact.Id;    
        newVisitConfirmation.Facility__c = newFacility.Id;
        newVisitConfirmation.Room__c = newRoom.Id;


        List<Visit_Confirmation__c> visitConfirmationList = new List<Visit_Confirmation__c>();
        visitConfirmationList.add(newVisitConfirmation);

        VisitConfirmationCreateVC.CreateVisitConfirmation(visitConfirmationList);

        System.assertEquals(1,1);

    }


    @isTest static void VisitConfirmationUpdateContactTests() {
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        insert testAccount;

        Contact testContact = new Contact();
        testContact.FirstName='Test' ;
        testContact.LastName='Test' ;
        testContact.Account = testAccount;
        testContact.Emergency_Contact_Relationship__c = 'Spouse';
        insert testContact;

        List<Contact> contactList = new List<Contact>();
        contactList.add(testContact);
        VisitConfirmationUpdateContact.updateContact(contactList);


        System.assertEquals(String.valueOf(testContact.Emergency_Contact_Relationship__c), 'Spouse');

    }


}