force-app/main/default/objects/Contact/fields/Office_Facility__c.field-meta.xml
<CustomField>
    <fullName>Office_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Occupants</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Room must be a cubicle or personal office.</errorMessage>
        <filterItems>
            <field>Room__c.Room_Type__c</field>
            <operation>equals</operation>
            <value>Cubicle, Personal Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Occupants</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Facility ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility__c/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <label>Default</label>
</RecordType>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/recordTypes/Room.recordType-meta.xml
<RecordType>
    <fullName>Room</fullName>
    <active>true</active>
    <label>Room</label>
</RecordType>

force-app/main/default/objects/User/fields/Contact_Record__c.field-meta.xml
<CustomField>
    <fullName>Contact_Record__c</fullName>
    <label>Contact Record</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Confirmation__c/Visit_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Visit Confirmation</label>
    <nameField>
        <displayFormat>VID-{0000}</displayFormat>
        <label>Visit Confirmation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Confirmations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Confirmation__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Service Appointment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Confirmation__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Visit Confirmations</relationshipLabel>
    <relationshipName>Visit_Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Confirmation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Visit Confirmations</relationshipLabel>
    <relationshipName>Visit_Confirmations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VisitConfirmationCreateVC.cls
public class VisitConfirmationCreateVC {
    
   @InvocableMethod
   public static void CreateVisitConfirmation(List<Visit_Confirmation__c> newVisitConfirmation) {
       for (Visit_Confirmation__c individualVisitConfirmation : newVisitConfirmation){
           VisitConfirmationCreateVC.createIndividualVisitConfirmation(individualVisitConfirmation);
       }
   }    
    
    public static void createIndividualVisitConfirmation(Visit_Confirmation__c newVisitConfirmation){

       newVisitConfirmation.Event_Type__c = String.valueOf(newVisitConfirmation.Event_Type__c);

       //We default owner to Bob if no Owner is provided
       if(newVisitConfirmation.OwnerId == NULL){
           User bob = [SELECT Id from User WHERE FirstName = 'bob.young.demo@mailinator.com'];
           newVisitConfirmation.OwnerId = bob.Id;     
       }
       
       User VisitOwner = [SELECT Id, Email, Contact_Record__c FROM User WHERE Id = : newVisitConfirmation.OwnerId];
       Contact VisitOwnerContact = [SELECT Id, Office_Facility__c, Room__c FROM Contact WHERE Id = :VisitOwner.Contact_Record__c LIMIT 1];
            
       //We default facility to Owners if none is provided.
       if(newVisitConfirmation.Facility__c == NULL){
            newVisitConfirmation.Facility__c = VisitOwnerContact.Office_Facility__c; 
       }
       
       //We default room to Owners if none is provided.
       if(newVisitConfirmation.Room__c == NULL){
            newVisitConfirmation.Room__c = VisitOwnerContact.Room__c; 
       }       


       insert newVisitConfirmation;
   }    
}